# Generated by Django 2.1.2 on 2018-10-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='note',
            name='author_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='common.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='common.Currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
