# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('to_address', models.CharField(max_length=140)),
                ('from_address', models.CharField(default='NSP <bookings@naturalselectionpromotions.com>', max_length=140)),
                ('subject', models.TextField(max_length=140)),
                ('body', models.TextField(default='')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, 'notification'), (1, 'confirmation'), (2, 'password')], default=0, null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('attachments', models.ManyToManyField(to='common.Upload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('to_number', models.CharField(max_length=15)),
                ('from_number', models.CharField(blank=True, max_length=15, null=True)),
                ('body', models.TextField(default='')),
                ('sent_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
