# Generated by Django 2.1.2 on 2018-10-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='modified_date',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
