# Generated by Django 2.1.2 on 2018-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationsnapshot',
            options={'ordering': ['-_timestamp'], 'verbose_name_plural': 'allocation_snapshots'},
        ),
        migrations.RemoveField(
            model_name='allocationsnapshot',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='allocationsnapshot',
            name='_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allocationsnapshot',
            name='is_realized',
            field=models.BooleanField(default=False),
        ),
    ]
