# Generated by Django 2.1.2 on 2018-11-08 17:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181108_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationsnapshot',
            name='allocation_data',
        ),
        migrations.AddField(
            model_name='allocationsnapshot',
            name='realized_allocation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='allocationsnapshot',
            name='target_allocation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'ITF24HR': 0.999}),
        ),
    ]
