# Generated by Django 2.1.2 on 2018-11-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181108_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
