# Generated by Django 2.1.2 on 2018-11-09 11:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_exchangeaccount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_allocation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('realized_allocation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_realized', models.BooleanField(default=False)),
                ('BTC_price', models.BigIntegerField(null=True)),
                ('_timestamp', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio.Portfolio')),
            ],
            options={
                'verbose_name_plural': 'allocations',
                'ordering': ['-_timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='allocationsnapshot',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='AllocationSnapshot',
        ),
    ]
