# Generated by Django 2.1.2 on 2018-11-09 13:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20181109_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='BTC_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='realized_allocation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='target_allocation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
