# Generated by Django 2.1.2 on 2018-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20181109_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='rebalanced_at',
            field=models.DateTimeField(null=True),
        ),
    ]
